name: kitab_at_tauhid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_html: ^0.8.2
  shared_preferences: ^0.4.3
  dynamic_theme: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri/Amiri-Regular.ttf
        - asset: fonts/Amiri/Amiri-Italic.ttf
          style: italic
        - asset: fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: fonts/Amiri/Amiri-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Katibeh
      fonts:
        - asset: fonts/Katibeh/Katibeh-Regular.ttf
    - family: Lateef
      fonts:
        - asset: fonts/Lateef/LateefRegOT.ttf
    - family: MarkaziText
      fonts:
        - asset: fonts/Markazi_Text/MarkaziText-Regular.ttf
    - family: Mirza
      fonts:
        - asset: fonts/Mirza/Mirza-Regular.ttf
        - asset: fonts/Mirza/Mirza-Medium.ttf
          weight: 200
        - asset: fonts/Mirza/Mirza-Bold.ttf
          weight: 700
        - asset: fonts/Mirza/Mirza-SemiBold.ttf
          weight: 400
    - family: Scheherazade
      fonts:
        - asset: fonts/Scheherazade/Scheherazade-Regular.ttf
        - asset: fonts/Scheherazade/Scheherazade-Bold.ttf
          weight: 700


    - family: Lora
      fonts:
        - asset: fonts/Lora/Lora-Regular.ttf
        - asset: fonts/Lora/Lora-Italic.ttf
          style: italic
        - asset: fonts/Lora/Lora-Bold.ttf
          weight: 700
        - asset: fonts/Lora/Lora-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Regular.ttf
        - asset: fonts/Oswald/Oswald-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
